// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKgesyuIZNEL0Ay0y8TzQd_EWm7A2NtCQ',
    appId: '1:540433544607:android:ee839f95af5ca974f179aa',
    messagingSenderId: '540433544607',
    projectId: 'rusticgram-e7673',
    storageBucket: 'rusticgram-e7673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtSFK-wMa_3pt5SfNpOcI9YoonDju5lg',
    appId: '1:540433544607:ios:869db0879a05a1f3f179aa',
    messagingSenderId: '540433544607',
    projectId: 'rusticgram-e7673',
    storageBucket: 'rusticgram-e7673.appspot.com',
    androidClientId: '540433544607-2th5lavu15dltc7v5g9o3ba09n28bthm.apps.googleusercontent.com',
    iosClientId: '540433544607-01855q4kea64servmkvmbees2l4ai56n.apps.googleusercontent.com',
    iosBundleId: 'com.rusticgram.app',
  );

}